AllTestCase:
- description: Automated test
  enabled: true
  expected: 20
  id: 0
  index: 3
  key: ethernet
  name: Ethernet Test
  start: /tmp/factorytest_bin/factory_test_ethernet
  type: automated
- description: Automated test
  enabled: true
  expected: MB/s
  id: 1
  index: 0
  key: usb
  name: USB Test
  start: /tmp/factorytest_bin/factory_test_usb
  type: automated
- description: Manual test
  enabled: true
  expected: null
  id: 2
  index: 1
  key: led
  name: LED Test
  start: /tmp/factorytest_bin/factory_test_led
  stop: /tmp/factorytest_bin/factory_test_close_led
  tips: Check if the LED is blinking
  type: manual
- description: Manual test
  enabled: true
  expected: null
  id: 3
  index: 2
  key: hdmi
  name: HDMI Test
  start: /tmp/factorytest_bin/factory_test_hdmi
  tips: Connect HDMI and check for a display
  type: manual
- description: Manual test
  enabled: true
  expected: code 116 (KEY_POWER), value 1
  id: 4
  index: 4
  key: key-power
  name: Power Button Test
  start: /tmp/factorytest_bin/factory_test_key power
  tips: Press the Power button
  type: manual
- description: Manual test
  enabled: true
  expected: code 87 (KEY_F11), value 1
  id: 5
  index: 5
  key: key-loader
  name: Loader Button Test
  start: /tmp/factorytest_bin/factory_test_key loader
  tips: Press the Loader button
  type: manual
TestFinished: /tmp/factorytest_bin/factory_test_finished
