AllTestCase:
- description: 自动测试
  enabled: true
  expected: 20
  id: 0
  index: 3
  key: ethernet
  name: 以太网测试
  start: /tmp/factorytest_script/factory_test_ethernet.sh
  type: automated
- description: 自动测试
  enabled: true
  expected: MB/s
  id: 1
  index: 0
  key: usb
  name: USB测试
  start: /tmp/factorytest_script/factory_test_usb.sh
  type: automated
- description: 手动测试
  enabled: true
  expected: null
  id: 2
  index: 1
  key: led
  name: LED测试
  start: /tmp/factorytest_script/factory_test_led.sh
  stop: /tmp/factorytest_script/factory_test_close_led.sh
  tips: 请查看LED是否闪烁
  type: manual
- description: 手动测试
  enabled: true
  expected: null
  id: 3
  index: 2
  key: hdmi
  name: HDMI测试
  start: /tmp/factorytest_script/factory_test_hdmi.sh
  tips: 请连接HDMI查看是否有画面
  type: manual
- description: 手动测试
  enabled: true
  expected: code 116 (KEY_POWER), value 1
  id: 4
  index: 4
  key: key-power
  name: Power按键测试
  start: /tmp/factorytest_script/factory_test_key.sh power
  tips: 请按下Power按键
  type: manual
- description: 手动测试
  enabled: true
  expected: code 87 (KEY_F11), value 1
  id: 5
  index: 5
  key: key-loader
  name: Loader按键测试
  start: /tmp/factorytest_script/factory_test_key.sh loader
  tips: 请按下Loader按键
  type: manual
TestFinished: /tmp/factorytest_script/factory_test_finished.sh
