AllTestCase:
  - start: route_ip=$(ip route 2>/dev/null | awk '/via/ {print $3}') && { [ -n "$route_ip" ] && ping -I eth0 -c 5 $route_ip | awk -F' |%' '/packet loss/ {print "loss="$6; exit}' || echo "loss=100"; }
    enabled: true
    expected: 20
    id: 0
    index: 3
    name: 以太网测试
    key: ethernet
    type: 自动测试
  - start: dd if=/dev/zero of=/mnt/udisk/testfile bs=1M count=10 >/dev/null 2>&1 && sync && result=$(dd if=/mnt/udisk/testfile of=/dev/null bs=1M 2>&1) && rm /mnt/udisk/testfile && echo $result
    enabled: true
    expected: MB/s
    id: 1
    index: 0
    name: USB测试
    key: usb
    type: 自动测试
  - start: echo 1 >/sys/class/gpio/gpio138/value && echo 1 >/sys/class/gpio/gpio141/value && sleep 0.5 && echo 0 >/sys/class/gpio/gpio138/value && echo 0 >/sys/class/gpio/gpio141/value && sleep 0.5
    stop: echo 0 > /sys/class/gpio/gpio138/value; echo 0 > /sys/class/gpio/gpio141/value
    enabled: true
    id: 2
    index: 1
    name: LED测试
    key: led
    type: 手动测试
    tips: 请查看LED是否闪烁
  - start: cat /sys/class/drm/card0-HDMI-A-1/status
    enabled: true
    id: 3
    index: 2
    name: HDMI测试
    key: hdmi
    type: 手动测试
    tips: 请连接HDMI查看是否有画面
  - start: evtest /dev/input/event0
    enabled: false
    id: 4
    index: 4
    name: Power按键测试
    key: key-power
    type: 手动测试
    tips: 请按下Power按键
    expected: code 87 (KEY_F11), value 1
  - start: evtest /dev/input/event1
    enabled: true
    id: 5
    index: 5
    name: Loader按键测试
    key: key-loader
    type: 手动测试
    tips: 请按下Loader按键
    expected: code 87 (KEY_F11), value 1